name: error_classification
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy<2
  - librosa
  - soxr
  - scipy
  - soundfile
  - audioread
  - pandas
  - tensorflow
  - keras
